### ISSUE TITLE
build_box initialize ArgumentError should indicate what is valid

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand-packaging#165]
I'm trying to get a build box this morning and couldn't figure out what _was_ valid. It'd be nice if this error message said A not in list of [X, Y, Z]

```
rake aborted!
ArgumentError: Invalid dist selected: deb
/home/jeff/ondemand/misc/packaging/lib/ood_packaging/build_box.rb:15:in `initialize'
/home/jeff/ondemand/misc/packaging/lib/ood_packaging/tasks.rb:9:in `new'
/home/jeff/ondemand/misc/packaging/lib/ood_packaging/tasks.rb:9:in `block (3 levels) in <top (required)>'
/home/jeff/vendor/bundle/ruby/2.7.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/home/jeff/.rvm/gems/ruby-2.7.1/bin/ruby_executable_hooks:22:in `eval'
/home/jeff/.rvm/gems/ruby-2.7.1/bin/ruby_executable_hooks:22:in `<main>'
```

**Comment by treydock** [comment]
Fixed with #166
