### ISSUE TITLE
ondemand scl doesn't hold core gems

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand-packaging#237]
A simple test just loads the `ondemand` scl package and then attempts to step into `irb`.
```
[johrstrom ~()]  . scl_source enable ondemand
[johrstrom ~()]  irb
/opt/rh/rh-ruby30/root/usr/share/rubygems/rubygems/specification.rb:1408:in `rescue in block in activate_dependencies': Could not find 'reline' (>= 0.1.5) among 164 total gem(s) (Gem::MissingSpecError)
Checked in 'GEM_PATH=/opt/ood/ondemand/root/usr/share/gems/3.0:/opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.0-0.rc5:/opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.0-0.rc4:/opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.0:/users/PZS0714/johrstrom/.gem/ruby:/opt/rh/rh-ruby30/root/usr/share/gems:/opt/rh/rh-ruby30/root/usr/local/share/gems:/opt/ood/ondemand/root/usr/share/gems/3.0ondemand/root/usr/share/gems:/opt/ood/ondemand/root/usr/share/gems/3.0ondemand/root/usr/local/share/gems' at: /opt/rh/rh-ruby30/root/usr/share/gems/specifications/irb-1.3.5.gemspec, execute `gem env` for more information
        from /opt/rh/rh-ruby30/root/usr/share/rubygems/rubygems/specification.rb:1405:in `block in activate_dependencies'
        from /opt/rh/rh-ruby30/root/usr/share/rubygems/rubygems/specification.rb:1394:in `each'
        from /opt/rh/rh-ruby30/root/usr/share/rubygems/rubygems/specification.rb:1394:in `activate_dependencies'
        from /opt/rh/rh-ruby30/root/usr/share/rubygems/rubygems/specification.rb:1376:in `activate'
        from /opt/rh/rh-ruby30/root/usr/share/rubygems/rubygems.rb:299:in `block in activate_bin_path'
        from /opt/rh/rh-ruby30/root/usr/share/rubygems/rubygems.rb:298:in `synchronize'
        from /opt/rh/rh-ruby30/root/usr/share/rubygems/rubygems.rb:298:in `activate_bin_path'
        from /opt/rh/rh-ruby30/root/usr/bin/irb:23:in `<main>'
/opt/rh/rh-ruby30/root/usr/share/rubygems/rubygems/dependency.rb:311:in `to_specs': Could not find 'reline' (>= 0.1.5) among 164 total gem(s) (Gem::MissingSpecError)
Checked in 'GEM_PATH=/opt/ood/ondemand/root/usr/share/gems/3.0:/opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.0-0.rc5:/opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.0-0.rc4:/opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.0:/users/PZS0714/johrstrom/.gem/ruby:/opt/rh/rh-ruby30/root/usr/share/gems:/opt/rh/rh-ruby30/root/usr/local/share/gems:/opt/ood/ondemand/root/usr/share/gems/3.0ondemand/root/usr/share/gems:/opt/ood/ondemand/root/usr/share/gems/3.0ondemand/root/usr/local/share/gems' , execute `gem env` for more information
        from /opt/rh/rh-ruby30/root/usr/share/rubygems/rubygems/specification.rb:1406:in `block in activate_dependencies'
        from /opt/rh/rh-ruby30/root/usr/share/rubygems/rubygems/specification.rb:1394:in `each'
        from /opt/rh/rh-ruby30/root/usr/share/rubygems/rubygems/specification.rb:1394:in `activate_dependencies'
        from /opt/rh/rh-ruby30/root/usr/share/rubygems/rubygems/specification.rb:1376:in `activate'
        from /opt/rh/rh-ruby30/root/usr/share/rubygems/rubygems.rb:299:in `block in activate_bin_path'
        from /opt/rh/rh-ruby30/root/usr/share/rubygems/rubygems.rb:298:in `synchronize'
        from /opt/rh/rh-ruby30/root/usr/share/rubygems/rubygems.rb:298:in `activate_bin_path'
        from /opt/rh/rh-ruby30/root/usr/bin/irb:23:in `<main>'
```

`reline` is shown to be in this location.
```
[johrstrom ~()]  gem which reline
/opt/rh/rh-ruby30/root/usr/share/ruby/reline.rb
```

As an aside/possibly a red herring these PATHs seem to be wrong (from `gem env`). they seem to be missing a `/` after `3.0`.
```
  - GEM PATHS:
     - /opt/ood/ondemand/root/usr/share/gems/3.0ondemand/root/usr/share/gems
     - /opt/ood/ondemand/root/usr/share/gems/3.0ondemand/root/usr/local/share/gems
```

**Comment by johrstrom** [comment]
`unset GEM_PATH` seems to fix it, but I'm still trying to track down what may fix it.

**Comment by treydock** [comment]
Might be as simple as this:

```
export GEM_PATH=$(gem env gempath)
```

Then when OnDemand gem locations are added, they will be added to the existing system paths.

**Comment by treydock** [comment]
That trick doesn't work.  For some reason `GEM_PATH` is missing the necessary path when you do `gem env gempath`, at least for reline gem.

**Comment by johrstrom** [comment]
I tracked it down to this file. Attached is a slightly modified version to debug with.

```
[johrstrom gems()]  irb
irb(main):001:0> Gem.method(:default_dirs).source_location
=> ["/opt/rh/rh-ruby30/root/usr/share/rubygems/rubygems/defaults/operating_system.rb", 106]
```


[operating_system.rb.txt](https://github.com/OSC/ondemand-packaging/files/10687032/operating_system.rb.txt)

From what I can glean here, it's expecting us (the `ondemand` scl) to provide system gems?
```ruby
    def default_dir
      prefix = scl_prefix
      puts "looking for #{scl_prefix}"
      if Gem.default_dirs.key?(:"#{prefix}system")
        Gem.default_dirs[:"#{prefix}system"][:gem_dir]
      else
        Gem.default_dirs[:"system"][:gem_dir]
      end
    end
```

In any case, I'm beginning to wonder how ondemand works at all and how _it_ finds system gems.

**Comment by treydock** [comment]
I think Ruby's load paths are different than what GEM_PATH prints:

```
[root@webdev02 ~]# scl enable rh-ruby27 -- ruby -e 'puts $:'
/opt/rh/rh-ruby27/root/usr/local/share/ruby/site_ruby
/opt/rh/rh-ruby27/root/usr/local/lib64/ruby/site_ruby
/opt/rh/rh-ruby27/root/usr/share/ruby/vendor_ruby
/opt/rh/rh-ruby27/root/usr/lib64/ruby/vendor_ruby
/opt/rh/rh-ruby27/root/usr/share/rubygems
/opt/rh/rh-ruby27/root/usr/share/ruby
/opt/rh/rh-ruby27/root/usr/lib64/ruby
```

I tried this but get different errors:

```
export GEM_PATH=$(ruby -e "puts ($:).join(':')")
```

```
[root@webdev02 ~]# scl enable ondemand -- irb
/opt/rh/rh-ruby30/root/usr/share/rubygems/rubygems.rb:278:in `find_spec_for_exe': can't find gem irb (>= 0.a) with executable irb (Gem::GemNotFoundException)
        from /opt/rh/rh-ruby30/root/usr/share/rubygems/rubygems.rb:297:in `activate_bin_path'
        from /opt/rh/rh-ruby30/root/usr/bin/irb:23:in `<main>'
```

Went to test on RHEL8 OnDemand but irb isn't even installed by default, once that's installed:

```
[root@webdev07 ~]# scl enable ondemand -- irb
irb(main):001:0> 
```

So the issue is just the weirdness with RHEL7 and SCL installed Ruby.

**Comment by treydock** [comment]
This is why it works for OnDemand:

```
[root@webdev02 ~]# source /opt/ood/ondemand/enable 
[root@webdev02 ~]# irb
irb(main):001:0> 
```

Is it correct that the OnDemand files that load SCL run `source` on the SCL ?

**Comment by johrstrom** [comment]
Yea looks like it does from this profile.

https://github.com/OSC/ondemand/blob/master/nginx_stage/etc/profile

I think the major difference is that `frame-renderer` has `shellwords` (a system gem) as a dependency in the Gemfile.

So the stack is 
Passenger -> bundler -> exception, because bundler can't find system gems in that moment.

```
/opt/rh/rh-ruby30/root/usr/share/gems/gems/bundler-2.2.33/lib/bundler/definition.rb:480:in `materialize': Could not find shellwords-0.1.0 in any of the sources (Bundler::GemNotFound)
	from /opt/rh/rh-ruby30/root/usr/share/gems/gems/bundler-2.2.33/lib/bundler/definition.rb:185:in `specs'
	from /opt/rh/rh-ruby30/root/usr/share/gems/gems/bundler-2.2.33/lib/bundler/definition.rb:233:in `specs_for'
	from /opt/rh/rh-ruby30/root/usr/share/gems/gems/bundler-2.2.33/lib/bundler/runtime.rb:18:in `setup'
	from /opt/rh/rh-ruby30/root/usr/share/gems/gems/bundler-2.2.33/lib/bundler.rb:150:in `setup'
	from /opt/rh/rh-ruby30/root/usr/share/gems/gems/bundler-2.2.33/lib/bundler/setup.rb:20:in `block in <top (required)>'
	from /opt/rh/rh-ruby30/root/usr/share/gems/gems/bundler-2.2.33/lib/bundler/ui/shell.rb:136:in `with_level'
	from /opt/rh/rh-ruby30/root/usr/share/gems/gems/bundler-2.2.33/lib/bundler/ui/shell.rb:88:in `silence'
	from /opt/rh/rh-ruby30/root/usr/share/gems/gems/bundler-2.2.33/lib/bundler/setup.rb:20:in `<top (required)>'
	from <internal:/opt/rh/rh-ruby30/root/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:160:in `require'
	from <internal:/opt/rh/rh-ruby30/root/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:160:in `rescue in require'
	from <internal:/opt/rh/rh-ruby30/root/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:149:in `require'
<internal:/opt/rh/rh-ruby30/root/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- bundler/setup (LoadError)
	from <internal:/opt/rh/rh-ruby30/root/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require'
```

Let me see if just not requiring system gems in the Gemfile can move us forward here.

**Comment by treydock** [comment]
It will be a non-issue in a year when we drop EL7 support as that's when RedHat will EOL RHEL7.

**Comment by johrstrom** [comment]
Yea I'm going to close saying we can't support ruby apps with default gems in the Gemfile on RHEL/7. I may literally be the only person who's done this, but outside of that I would say it's very limited in terms of other sites running into this issue. 1, 2 tops.  You would have to have a ruby passenger app (which most sites do not) plus have added a standard gem into the Gemfile, so I can't imagine lot's of people running into the same issue.
